### ISSUE TITLE
Decode URI in batch editor

### ISSUE THREAD

**Issue by axl411** [stephenwzl/BatchEditorApp#2]
for example: `/shopping/v1/entry_stats?entry_names=%E8%BF%91%E9%93%81%E5%9F%8E%E5%B8%82%E5%B9%BF%E5%9C%BA%2C%E7%99%BE%E8%81%94%E4%B8%AD%E7%8E%AF%E8%B4%AD%E7%89%A9%E5%B9%BF%E5%9C%BA%28%E7%9C%9F%E5%85%89%E8%B7%AF%E5%BA%97%29&entry_type=%E5%95%86%E5%9C%BA%E5%85%A5%E5%8F%A3` should be easier to read if it is `/shopping/v1/entry_stats?entry_names=近铁城市广场,百联中环购物广场(真光路店)&entry_type=商场入口`

**Comment by axl411** [comment]
On the left side it should always be URI encoded, but on the right side it should decode the URI if possible

**Comment by stephenwzl** [comment]
OK

**Comment by stephenwzl** [comment]
Batch => About Batch => Check for Update
